image: Visual Studio 2017

build_script:
- echo Building opus library
- if not exist "./temp/opus" mkdir "./temp/opus"
- cd ./temp/opus
- cmake -G "Visual Studio 15 Win64" ../../vendor/opus/
- cd ../../
- ".\vendor\opus\win32\genversion.bat" ".\vendor\opus\win32\version.h" PACKAGE_VERSION
- msbuild ./temp/opus/opus.vcxproj /p:PlatformToolset=v141 /p:Configuration=Release /p:Platform=x64 /p:OutDir=../../libs/Release/
- echo Building OpenAL library
- if not exist "./temp/openal" mkdir "./temp/openal"
- cd ./temp/openal
- cmake -G "Visual Studio 15 Win64" -DLIBTYPE=STATIC -DALSOFT_BACKEND_DSOUND=OFF -DALSOFT_BACKEND_WASAPI=OFF  ../../vendor/openal/
- cd ../../
- msbuild ./temp/openal/OpenAL.vcxproj /p:PlatformToolset=v141 /p:Configuration=Release /p:Platform=x64 /p:OutDir=../../libs/Release/
- echo Building alt-voice library
- if not exist "./temp/alt-voice" mkdir "./temp/alt-voice"
- cd ./temp/alt-voice
- cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 Win64" ../../
- cd ../../
- msbuild ./temp/alt-voice/alt-voice.vcxproj /p:PlatformToolset=v141 /p:Configuration=Release /p:Platform=x64 /p:OutDir=../../bin/Release/
- if not exist "./bin/Release" mkdir "./bin/Release"
- copy /y .\temp\alt-voice\Release\alt-voice.lib .\bin\Release\alt-voice.lib
- echo "alt-voice built finished"


clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

artifacts:
  - path: bin\alt-voice.dll
    name: alt-voice